Fix cast in command-line parsing
Casting NULL to char breaks the build, as argv is a char* array.

 anyoption.cpp: In member function 'void AnyOption::useCommandArgs(int, QStringList)':
 anyoption.cpp:385:34: error: invalid conversion from 'char' to 'char*' [-fpermissive]
   argv[_argv.size()] = ((char)NULL);