Avoid conflict with std::launch
The launch() function would conflict with std::launch from future.h and
cause the build to fail with gcc 6.4[1]:

  main.cpp: In function ‘int main(int, char**)’:
  main.cpp:106:10: error: reference to ‘launch’ is ambiguous
       if (!launch(cmdopts)) {
            ^~~~~~

To prevent this behaviour, rename launch() to setupOptions(), giving it
a more meaningful name.

[1] http://autobuild.buildroot.org/results/bd0/bd02f3dadb710f03cd5026b9da1d7f32552c6c59/build-end.log